apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app:  myjavaapp
    
spec:
  type: LoadBalancer
  ports:
  - targetPort: http
    port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjavaapp
    
